version: '2'
services:
  omeka-s-db-backup:
    image: libapps-admin.uncw.edu:8000/randall-dev/test-sidekick
    environment:
      ROOT_PASSWORD: '***REMOVED***'
      DB_NAMES: omeka-s
      DB_HOST: omeka-s-db
    volumes:
    - /home/randall/volumes/backups/Backups/omeka-s:/backups
  omeka-s:
    image: libapps-admin.uncw.edu:8000/randall-dev/omeka-s:v2.1.2
    volumes:
    - /home/randall/volumes/omeka-s/files:/var/www/html/files
    links:
    - omeka-s-db:database
  omeka-s-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: omeka-s-db
  omeka-s-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: '***REMOVED***'
      TZ: America/New_York
    volumes:
    - /home/randall/volumes/omeka-s/omeka-s-data:/var/lib/mysql