version: '3.7'

volumes:
  db_data:
  solr_data:

networks:
  db_network:
    driver: bridge
  solr_network:
    driver: bridge

services:
  omeka:
    container_name: omeka
    image: libapps-admin.uncw.edu:8000/randall-dev/omeka-s:updating
    platform: linux/x86_64/v8
    env_file: .env
    build: ./app
    volumes:
      # - ./app/config/local.config.php:/var/www/html/config/local.config.php
      - ./app/files:/var/www/html/files
      - ./app/config/php.ini:/usr/local/etc/php/php.ini
      # - ./app/themes/custom:/var/www/html/themes/custom
    ports:
      - "8008:80"
    networks:
      - db_network
      - solr_network
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: mysql/mysql-server:8.0.16
    platform: linux/x86_64/v8
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db_autoimport:/docker-entrypoint-initdb.d/
    networks:
      - db_network
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  pma:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: pma
    env_file: .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_ARBITRARY: 0
      PMA_PORT: 3306
    networks:
      - db_network
    depends_on:
      - db
    ports:
      - "8113:80"
    restart: always

  solr:
    container_name: solr
    image: amd64/solr:8.10
    platform: linux/x86_64/v8
    networks:
      - solr_network
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command: ["solr-precreate", "omeka"]
    restart: always

